const employees = [
  {
    id: 101,
    name: "Alex Mercer",
    email: "alex.mercer@company.com",
    password: "123",
    taskCount: {
      active: 2,
      newTask: 1,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Client Meeting",
        description: "Prepare slides for the project kickoff.",
        taskDate: "2026-05-10",
        category: "Management",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Update UI",
        description: "Fix the navigation bar responsiveness on mobile.",
        taskDate: "2026-05-08",
        category: "Design",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Bug Fix #402",
        description: "Resolved the issue where login button stayed disabled.",
        taskDate: "2026-05-01",
        category: "Development",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Hardware Check",
        description: "Inspect the laboratory servers for overheating.",
        taskDate: "2026-05-25",
        category: "Engineering",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Database Migration",
        description:
          "Attempted to migrate legacy data, but connection timed out.",
        taskDate: "2026-04-30",
        category: "Backend",
      },
    ],
  },
  {
    id: 102,
    name: "Sarah Connor",
    email: "sarah.connor@company.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Client Meeting",
        description: "Prepare slides for the project kickoff.",
        taskDate: "2026-05-10",
        category: "Management",
      },
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Review Proposals",
        description: "Check the new vendor proposals for the server upgrade.",
        taskDate: "2026-05-12",
        category: "Admin",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Quarterly Report",
        description: "Finalized the Q1 expense report.",
        taskDate: "2026-04-15",
        category: "Finance",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Team Building",
        description: "Organized the virtual coffee hour.",
        taskDate: "2026-04-20",
        category: "Culture",
      },
    ],
  },
  {
    id: 103,
    name: "Tony Stark",
    email: "tony.stark@company.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 1,
      failed: 0,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "AI Integration",
        description:
          "Start the Lyria 3 model integration for music generation.",
        taskDate: "2026-06-01",
        category: "Innovation",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Hardware Check",
        description: "Inspect the laboratory servers for overheating.",
        taskDate: "2026-05-25",
        category: "Engineering",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Suit Calibration",
        description: "Adjusted thruster output for better stability.",
        taskDate: "2026-03-10",
        category: "Defense",
      },
    ],
  },
  {
    id: 104,
    name: "Bruce Wayne",
    email: "bruce.wayne@company.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 0,
      completed: 1,
      failed: 1,
    },
    tasks: [
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Market Analysis",
        description: "Review the impact of competitors on Wayne Tech stock.",
        taskDate: "2026-05-15",
        category: "Business",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Charity Gala",
        description: "Hosted the annual children's hospital fundraiser.",
        taskDate: "2026-02-14",
        category: "Social",
      },
      {
        active: false,
        newTask: false,
        completed: false,
        failed: true,
        taskTitle: "Satellite Launch",
        description: "Orbit insertion failed due to software glitch.",
        taskDate: "2026-01-20",
        category: "Aerospace",
      },
    ],
  },
  {
    id: 105,
    name: "Diana Prince",
    email: "diana.prince@company.com",
    password: "123",
    taskCount: {
      active: 1,
      newTask: 1,
      completed: 2,
      failed: 0,
    },
    tasks: [
      {
        active: false,
        newTask: true,
        completed: false,
        failed: false,
        taskTitle: "Artifact Cataloging",
        description:
          "Document the new items arrived from the Mediterranean site.",
        taskDate: "2026-05-20",
        category: "History",
      },
      {
        active: true,
        newTask: false,
        completed: false,
        failed: false,
        taskTitle: "Exhibit Tour",
        description: "Lead the VIP tour for the Greco-Roman exhibit.",
        taskDate: "2026-05-22",
        category: "Education",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Linguistics Research",
        description: "Translated the ancient stone tablet inscriptions.",
        taskDate: "2026-04-05",
        category: "Research",
      },
      {
        active: false,
        newTask: false,
        completed: true,
        failed: false,
        taskTitle: "Security Review",
        description: "Checked the museum's overnight alarm systems.",
        taskDate: "2026-04-10",
        category: "Safety",
      },
    ],
  },
];

const admin = [
  {
    id: 1,
    email: "admin@company.com",
    password: "123",
    name: "Admin",
  },
];

export const setLocalStorage = () => {
  localStorage.setItem("employees", JSON.stringify(employees));
  localStorage.setItem("admin", JSON.stringify(admin));
};
export const getLocalStorage = () => {
  const employees = JSON.parse(localStorage.getItem("employees"));
  const admin = JSON.parse(localStorage.getItem("admin"));
  return { employees, admin };
};
